name: pass_vault
description: Your passwords, secured.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  google_fonts: ^4.0.3
  sliver_tools: ^0.2.9
  flutter_native_splash: ^2.2.17
  equatable: ^2.0.5
  flutter_svg: ^2.0.0+1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
#  flutter_launcher_icons: "^0.11.0"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home_backdrop.png
    - assets/images/category_browser.svg
    - assets/images/category_mobile.svg
    - assets/images/category_payment.svg
    - assets/images/light_backdrop.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/logo.png"
#  min_sdk_android: 21
#  adaptive_icon_background: "#F64072"
#  adaptive_icon_foreground: "assets/images/logo.png"
#  web:
#    generate: true
#    image_path: "assets/images/logo.png"
#    background_color: "#F64072"
#    theme_color: "#F64072"
#  windows:
#    generate: true
#    image_path: "assets/images/logo.png"
#    icon_size: 48
#  macos:
#    generate: true
#    image_path: "assets/images/logo.png"